# Generated by Django 4.0.2 on 2023-03-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
